import { useEffect, useState, type ReactNode } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { useSubscription } from '../../contexts/SubscriptionContext';
import { UpgradeGate } from '../common/UpgradeGate';
import { getCourseById, curriculumCourses } from '../../data/curriculum';
import { trackCurriculumCourseCompleted, trackCurriculumLessonCompleted } from '../../lib/analytics';
import { completeLesson, getCourseLockState, saveLessonNotes } from '../../lib/curriculum-progress';
import { useCurriculumState } from './curriculumState';
import './LessonView.css';

function renderInlineMarkdown(text: string): ReactNode[] {
  const parts = text.split(/(\*\*[^*]+\*\*)/g).filter(Boolean);

  return parts.map((part, index) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={`${part}-${index}`}>{part.slice(2, -2)}</strong>;
    }

    return <span key={`${part}-${index}`}>{part}</span>;
  });
}

function renderMarkdownBody(body: string): ReactNode[] {
  return body
    .trim()
    .split(/\n\s*\n/)
    .filter(Boolean)
    .map((block, index) => {
      const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);

      if (lines.every((line) => line.startsWith('- '))) {
        return (
          <ul key={`list-${index}`} className="lesson-body-list">
            {lines.map((line) => (
              <li key={line}>{renderInlineMarkdown(line.slice(2))}</li>
            ))}
          </ul>
        );
      }

      if (lines.every((line) => /^\d+\.\s/.test(line))) {
        return (
          <ol key={`ordered-${index}`} className="lesson-body-list">
            {lines.map((line) => (
              <li key={line}>{renderInlineMarkdown(line.replace(/^\d+\.\s/, ''))}</li>
            ))}
          </ol>
        );
      }

      return (
        <p key={`paragraph-${index}`} className="lesson-body-paragraph">
          {renderInlineMarkdown(lines.join(' '))}
        </p>
      );
    });
}

export function LessonView() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { hasAccess } = useSubscription();
  const { courseId, lessonId } = useParams();
  const { curriculumState, setCurriculumState } = useCurriculumState();
  const [notes, setNotes] = useState('');
  const [showCompleteFlash, setShowCompleteFlash] = useState(false);

  const course = courseId ? getCourseById(courseId) : undefined;
  const courseProgress = course && curriculumState ? curriculumState.progress.courses[course.id] : undefined;
  const lesson = course?.lessons.find((entry) => entry.id === lessonId);
  const lessonProgress = lesson && courseProgress ? courseProgress.lessons[lesson.id] : undefined;
  const noteValue = lessonProgress?.notes ?? '';

  useEffect(() => {
    setNotes(noteValue);
  }, [noteValue]);

  useEffect(() => {
    if (!showCompleteFlash) {
      return undefined;
    }

    const timer = window.setTimeout(() => setShowCompleteFlash(false), 1200);
    return () => window.clearTimeout(timer);
  }, [showCompleteFlash]);

  if (!curriculumState) {
    return (
      <main className="lesson-page" id="main-content">
        <div className="container">
          <section className="lesson-empty">
            <div className="eyebrow">Curriculum</div>
            <h2>Take the Quick Pulse before opening lessons.</h2>
            <p className="lede">Lessons unlock from the personalized curriculum generated by your current assessment result.</p>
            <button className="hero-button" onClick={() => navigate('/', { state: { openQuickPulse: true } })}>
              Take Quick Pulse
            </button>
          </section>
        </div>
      </main>
    );
  }

  if (!course || !courseProgress || !lesson || !lessonProgress) {
    return (
      <main className="lesson-page" id="main-content">
        <div className="container">
          <section className="lesson-shell">
            <div className="lesson-card-kicker">Lesson Not Found</div>
            <h2>This lesson is not available in your current curriculum.</h2>
            <button className="ghost-button" onClick={() => navigate('/curriculum')}>
              Back to Curriculum
            </button>
          </section>
        </div>
      </main>
    );
  }

  const lockState = getCourseLockState(course, curriculumState.progress, curriculumState.result.scores, curriculumCourses);

  if (lockState.locked) {
    return (
      <main className="lesson-page" id="main-content">
        <div className="container">
          <section className="lesson-shell">
            <div className="lesson-card-kicker">Course Locked</div>
            <h2>{course.title}</h2>
            <p>Return to the curriculum overview and complete the prerequisite course before opening this lesson.</p>
            <button className="ghost-button" onClick={() => navigate('/curriculum')}>
              Back to Curriculum
            </button>
          </section>
        </div>
      </main>
    );
  }

  const lessonIndex = course.lessons.findIndex((entry) => entry.id === lesson.id);
  const previousLesson = lessonIndex > 0 ? course.lessons[lessonIndex - 1] : null;
  const nextLesson = lessonIndex < course.lessons.length - 1 ? course.lessons[lessonIndex + 1] : null;
  const lessonPercent = Math.round(((lessonIndex + 1) / course.lesson_count) * 100);
  const showCourseComplete = lessonIndex === course.lessons.length - 1 && courseProgress.completed;
  const isPremiumLesson = lessonIndex > 0 && !hasAccess('full_curriculum');

  const handleNotesChange = (value: string) => {
    setNotes(value);
    setCurriculumState((current) => {
      if (!current) {
        return current;
      }

      return {
        ...current,
        progress: saveLessonNotes(current.progress, course.id, lesson.id, value),
      };
    });
  };

  const handleComplete = () => {
    if (lessonProgress.completed || !curriculumState) {
      return;
    }

    const nextProgress = completeLesson(curriculumState.progress, course.id, lesson.id);
    const nextCourseProgress = nextProgress.courses[course.id];

    setCurriculumState({
      ...curriculumState,
      progress: nextProgress,
    });

    void trackCurriculumLessonCompleted(course.id, lesson.id, course.domain, user?.id ?? null);

    if (nextCourseProgress?.completed && !courseProgress.completed) {
      void trackCurriculumCourseCompleted(course.id, course.domain, user?.id ?? null);
    }

    setShowCompleteFlash(true);
  };

  return (
    <main className="lesson-page" id="main-content">
      <div className="container">
        <div className="lesson-topbar">
          <button className="lesson-back" onClick={() => navigate(`/curriculum/${course.id}`)}>
            ← Back to {course.title}
          </button>
        </div>

        <div className="lesson-progress-row">
          <div>
            <div className="lesson-card-kicker">
              Lesson {lessonIndex + 1} of {course.lesson_count} • {lesson.type}
            </div>
          </div>
          <span>{lessonPercent}%</span>
        </div>
        <div className="lesson-progress-track" aria-hidden="true">
          <div className="lesson-progress-fill" style={{ width: `${lessonPercent}%` }} />
        </div>

        <section className="lesson-shell">
          <h1>{lesson.title}</h1>

          {isPremiumLesson ? (
            <UpgradeGate feature="full_curriculum">
              <div>
                <div className="lesson-body">
                  {renderMarkdownBody(lesson.content.body)}
                </div>

                {lesson.content.prompt && (
                  <section className="lesson-prompt-box">
                    <div className="lesson-card-kicker">Exercise Prompt</div>
                    <p>{lesson.content.prompt}</p>
                  </section>
                )}

                <section className="lesson-takeaway">
                  <div className="lesson-card-kicker">Key Takeaway</div>
                  <p>{lesson.content.takeaway}</p>
                </section>

                <section className="lesson-notes">
                  <div className="lesson-card-kicker">Your Notes</div>
                  <textarea
                    value={notes}
                    onChange={(event) => handleNotesChange(event.target.value)}
                    placeholder="Capture reflections, examples, or how you will apply this lesson."
                    aria-label="Your notes"
                  />
                </section>
              </div>
            </UpgradeGate>
          ) : (
            <>
              <div className="lesson-body">
                {renderMarkdownBody(lesson.content.body)}
              </div>

              {lesson.content.prompt && (
                <section className="lesson-prompt-box">
                  <div className="lesson-card-kicker">Exercise Prompt</div>
                  <p>{lesson.content.prompt}</p>
                </section>
              )}

              <section className="lesson-takeaway">
                <div className="lesson-card-kicker">Key Takeaway</div>
                <p>{lesson.content.takeaway}</p>
              </section>

              <section className="lesson-notes">
                <div className="lesson-card-kicker">Your Notes</div>
                <textarea
                  value={notes}
                  onChange={(event) => handleNotesChange(event.target.value)}
                  placeholder="Capture reflections, examples, or how you will apply this lesson."
                  aria-label="Your notes"
                />
              </section>

              {showCourseComplete && (
                <section className="lesson-complete-card">
                  <div className="lesson-card-kicker">Course Complete</div>
                  <h2>{course.title} completed</h2>
                  <p>
                    You&apos;ve finished every lesson in this course. Return to the curriculum overview to continue the path or
                    retake Quick Pulse if you want to measure the growth signal you&apos;ve added.
                  </p>
                  <div className="lesson-complete-actions">
                    <button className="hero-button" onClick={() => navigate('/curriculum')}>
                      Return to Curriculum
                    </button>
                  </div>
                </section>
              )}
            </>
          )}

          {lesson.content.reading && (
            <p className="lesson-reading">
              📖 Recommended: <strong>{lesson.content.reading.title}</strong> by {lesson.content.reading.author}
            </p>
          )}
        </section>

        <div className="lesson-actions">
          <button
            className="ghost-button"
            onClick={() => previousLesson && navigate(`/curriculum/${course.id}/${previousLesson.id}`)}
            disabled={!previousLesson}
          >
            ← Previous
          </button>

          <div className="lesson-actions-right">
            <button
              className={`hero-button lesson-complete-action${showCompleteFlash ? ' is-success' : ''}`}
              onClick={handleComplete}
              disabled={lessonProgress.completed || isPremiumLesson}
            >
              {lessonProgress.completed ? 'Completed ✓' : isPremiumLesson ? 'Upgrade to Complete' : 'Mark Complete →'}
            </button>

            {nextLesson && (
              <button
                className="ghost-button"
                onClick={() => navigate(`/curriculum/${course.id}/${nextLesson.id}`)}
                disabled={!lessonProgress.completed || isPremiumLesson}
              >
                Next Lesson →
              </button>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
